name: Event-based workflow execution

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  fork:
    branches:
      - main
      
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TRIGGERED the main branch workflow - event based"


Reusable workflow:

new workflow: reuseme.yml

name: Reusable workflow

on: 
  workflow_call:

jobs:
  reusejob1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "MY REUSABLE JOB 1 - EXECUTED"

